// Builds the seeded "Example Repertoire" content for each side — one short
// Reactions line (with a branch, so Study's variant walkthrough has
// something to show) and one Others position, generated by actually
// playing the moves through the real chess engine rather than hand-typing
// piece maps, so the recorded data is guaranteed internally consistent.
import { startingPosition } from './chess';
import { createGameState, makeMove, type GameState } from './chessEngine';
import type { BoardFace, CardMode, GroupId, MoveNode, Opening, PromotionPiece, ReactionBoard, Card } from './types';

// Reactions boards don't use front/back for position — only for their
// study text (`.moves` stays empty, no shared position to speak of).
function reactionsFace(text: string): BoardFace {
  return {
    pieces: {},
    turn: 'w',
    castling: { wK: false, wQ: false, bK: false, bQ: false },
    enPassant: null,
    arrows: [],
    circles: [],
    text,
    moves: []
  };
}

interface PlyDef {
  from: string;
  to: string;
  promotion?: PromotionPiece;
  children?: PlyDef[];
}

function buildNodes(state: GameState, defs: PlyDef[], idFactory: () => string): MoveNode[] {
  return defs.map((def) => {
    const result = makeMove(state, def.from, def.to, def.promotion);
    return {
      id: idFactory(),
      san: result.san,
      from: def.from,
      to: def.to,
      promotion: def.promotion,
      piecesAfter: result.next.pieces,
      turnAfter: result.next.turn,
      castlingAfter: result.next.castling,
      enPassantAfter: result.next.enPassant,
      addedArrows: [],
      addedCircles: [],
      removedArrows: [],
      removedCircles: [],
      children: def.children ? buildNodes(result.next, def.children, idFactory) : []
    };
  });
}

function playLine(moves: { from: string; to: string; promotion?: PromotionPiece }[]): GameState {
  let state = createGameState(startingPosition(), 'w');
  for (const m of moves) state = makeMove(state, m.from, m.to, m.promotion).next;
  return state;
}

function newReactionsCard(
  idFactory: () => string,
  openingId: string,
  order: number,
  name: string,
  frontText: string,
  line: PlyDef[]
): Card {
  const board: ReactionBoard = {
    id: idFactory(),
    order: 0,
    pieces: startingPosition(),
    turn: 'w',
    castling: { wK: true, wQ: true, bK: true, bQ: true },
    enPassant: null,
    arrows: [],
    circles: [],
    recording: buildNodes(createGameState(startingPosition(), 'w'), line, idFactory),
    front: reactionsFace(frontText),
    back: reactionsFace('')
  };
  return {
    id: idFactory(),
    openingId,
    order,
    name,
    mode: 'reactions' as CardMode,
    boards: [board]
  };
}

function newOthersCard(
  idFactory: () => string,
  openingId: string,
  order: number,
  name: string,
  frontText: string,
  backText: string,
  moves: { from: string; to: string; promotion?: PromotionPiece }[],
  arrowFrom: string,
  arrowTo: string,
  circleSquare: string
): Card {
  const state = playLine(moves);
  // Front is the bare position (the question); back adds the answer arrow
  // and circle — a small showcase of the front/back split now that the two
  // sides can actually differ.
  const front: BoardFace = {
    pieces: { ...state.pieces },
    turn: state.turn,
    castling: { ...state.castling },
    enPassant: state.enPassant,
    arrows: [],
    circles: [],
    text: frontText,
    moves: []
  };
  const back: BoardFace = {
    pieces: { ...state.pieces },
    turn: state.turn,
    castling: { ...state.castling },
    enPassant: state.enPassant,
    arrows: [{ from: arrowFrom, to: arrowTo, color: 'green' }],
    circles: [{ square: circleSquare, color: 'green' }],
    text: backText,
    moves: []
  };
  const board: ReactionBoard = {
    id: idFactory(),
    order: 0,
    pieces: state.pieces,
    turn: state.turn,
    castling: state.castling,
    enPassant: state.enPassant,
    arrows: [],
    circles: [],
    recording: [],
    front,
    back
  };
  return {
    id: idFactory(),
    openingId,
    order,
    name,
    mode: 'others' as CardMode,
    boards: [board]
  };
}

export function buildExampleContent(
  group: GroupId,
  repertoireId: string,
  idFactory: () => string
): { openings: Opening[]; cards: Card[] } {
  const openingId = idFactory();

  if (group === 'white') {
    // 1.e4 e5 2.Nf3 Nc6 3.Bc4, then Black's two common replies: 3...Bc5
    // (main line) and 3...Nf6 (the variation shown in Study's walkthrough).
    const line: PlyDef[] = [
      {
        from: 'e2',
        to: 'e4',
        children: [
          {
            from: 'e7',
            to: 'e5',
            children: [
              {
                from: 'g1',
                to: 'f3',
                children: [
                  {
                    from: 'b8',
                    to: 'c6',
                    children: [
                      {
                        from: 'f1',
                        to: 'c4',
                        children: [
                          { from: 'f8', to: 'c5', children: [{ from: 'c2', to: 'c3' }] },
                          { from: 'g8', to: 'f6', children: [{ from: 'f3', to: 'g5' }] }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ];
    const cards = [
      newReactionsCard(
        idFactory,
        openingId,
        0,
        'Main line',
        "Play White's setup against the Italian — watch for Black's two common replies to Bc4.",
        line
      ),
      newOthersCard(
        idFactory,
        openingId,
        1,
        'Key position',
        "What's White's main plan in this position?",
        "Play d4! to challenge Black's center and open lines for the pieces.",
        [
          { from: 'e2', to: 'e4' },
          { from: 'e7', to: 'e5' },
          { from: 'g1', to: 'f3' },
          { from: 'b8', to: 'c6' },
          { from: 'f1', to: 'c4' },
          { from: 'f8', to: 'c5' },
          { from: 'c2', to: 'c3' }
        ],
        'd2',
        'd4',
        'd4'
      )
    ];
    return { openings: [{ id: openingId, repertoireId, name: 'Italian Game', order: 0 }], cards };
  }

  // Black: 1.e4 c5 2.<White's two common replies: Nf3 main line, Nc3 variation>.
  const line: PlyDef[] = [
    {
      from: 'e2',
      to: 'e4',
      children: [
        {
          from: 'c7',
          to: 'c5',
          children: [
            { from: 'g1', to: 'f3', children: [{ from: 'd7', to: 'd6' }] },
            { from: 'b1', to: 'c3', children: [{ from: 'b8', to: 'c6' }] }
          ]
        }
      ]
    }
  ];
  const cards = [
    newReactionsCard(
      idFactory,
      openingId,
      0,
      'Main line',
      "Play Black's setup against 1.e4 — watch for White's two common second moves.",
      line
    ),
    newOthersCard(
      idFactory,
      openingId,
      1,
      'Key position',
      'This is the Najdorf Sicilian. What move order got us here?',
      '1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6 — Black delays development to prepare ...e5 or ...b5.',
      [
        { from: 'e2', to: 'e4' },
        { from: 'c7', to: 'c5' },
        { from: 'g1', to: 'f3' },
        { from: 'd7', to: 'd6' },
        { from: 'd2', to: 'd4' },
        { from: 'c5', to: 'd4' },
        { from: 'f3', to: 'd4' },
        { from: 'g8', to: 'f6' },
        { from: 'b1', to: 'c3' },
        { from: 'a7', to: 'a6' }
      ],
      'a6',
      'b5',
      'a6'
    )
  ];
  return { openings: [{ id: openingId, repertoireId, name: 'Sicilian Defense', order: 0 }], cards };
}
